# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-21 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistname', models.CharField(max_length=255)),
                ('artistlinkname', models.CharField(max_length=255)),
                ('facebooklink', models.CharField(max_length=255)),
                ('soundcloudLink', models.CharField(max_length=255)),
                ('bandcampLink', models.CharField(max_length=255)),
                ('instagramLink', models.CharField(max_length=255)),
                ('othermediaLink', models.CharField(max_length=255)),
                ('pictureLink1', models.CharField(max_length=255)),
                ('pictureLink2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TourDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourdatetime', models.DateTimeField()),
                ('tourcity', models.CharField(max_length=50)),
                ('tourvenue', models.CharField(max_length=50)),
                ('tourinfourl', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('udpated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
    ]
