# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-20 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=255)),
                ('appmusiclink', models.CharField(max_length=255)),
                ('appsociallink', models.CharField(max_length=255)),
                ('appcontactemail', models.CharField(max_length=255)),
                ('appcity', models.CharField(max_length=255)),
                ('appstate', models.CharField(max_length=255)),
                ('appabout', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artistname', models.CharField(max_length=255)),
                ('artistbio', models.CharField(max_length=2000)),
                ('artisturlname', models.SlugField(max_length=255)),
                ('websiteLink', models.CharField(max_length=255)),
                ('facebookLink', models.CharField(max_length=255)),
                ('soundcloudLink', models.CharField(max_length=255)),
                ('bandcampLink', models.CharField(max_length=255)),
                ('instagramLink', models.CharField(max_length=255)),
                ('twitterLink', models.CharField(max_length=255)),
                ('spotLink', models.CharField(max_length=255)),
                ('youtubeLink', models.CharField(max_length=255)),
                ('playersoundcloudLink', models.CharField(max_length=255)),
                ('profileImage', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caption', models.CharField(max_length=150)),
                ('credit', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='NewsAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsdatetime', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('newsheadline', models.CharField(max_length=255)),
                ('newsstory', models.CharField(max_length=2000)),
                ('newsimgcred', models.CharField(max_length=255)),
                ('newsimg', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='TourDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourdatetime', models.DateTimeField()),
                ('tourcity', models.CharField(max_length=50)),
                ('tourvenue', models.CharField(max_length=50)),
                ('tourinfourl', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeradmin.ArtistProfile')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('udpated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
    ]
