# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-03 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeradmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='currentArtist',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
