# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-22 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeradmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=255)),
                ('appmusiclink', models.CharField(max_length=255)),
                ('appsociallink', models.CharField(max_length=255)),
                ('appcontactemail', models.CharField(max_length=255)),
                ('appcity', models.CharField(max_length=255)),
                ('appstate', models.CharField(max_length=255)),
                ('appabout', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
