# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-22 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeradmin', '0002_artistapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistprofile',
            old_name='artistlinkname',
            new_name='artisturlname',
        ),
        migrations.RenameField(
            model_name='artistprofile',
            old_name='facebooklink',
            new_name='facebookLink',
        ),
        migrations.RenameField(
            model_name='artistprofile',
            old_name='othermediaLink',
            new_name='playersoundcloudLink',
        ),
        migrations.RenameField(
            model_name='artistprofile',
            old_name='pictureLink2',
            new_name='twitterLink',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='artistbio',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='websiteLink',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artistapplication',
            name='appabout',
            field=models.CharField(max_length=2000),
        ),
    ]
