# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-22 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeradmin', '0003_auto_20180322_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdates',
            name='artist_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bikeradmin.ArtistProfile'),
            preserve_default=False,
        ),
    ]
