# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-11 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeradmin', '0004_auto_20180605_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='artistPriority',
            field=models.IntegerField(default=1),
        ),
    ]
