# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-23 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeradmin', '0004_tourdates_artist_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsdatetime', models.DateTimeField()),
                ('newsheadline', models.CharField(max_length=255)),
                ('newsstory', models.CharField(max_length=2000)),
                ('newsimglink', models.CharField(max_length=255)),
                ('newsimgcred', models.CharField(max_length=255)),
            ],
        ),
    ]
