# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-23 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeradmin', '0005_newsannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='youtubeLink',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
