# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-24 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikeradmin', '0006_artistprofile_youtubelink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistprofile',
            old_name='pictureLink1',
            new_name='spotLink',
        ),
    ]
